qossmic/deptrac

- README.md
Just add the build status of travis master in the readme page.
> Add travis build status to readme

- src/Formatter/ConsoleFormatter.php
- src/Tests/Formatter/ConsoleFormatterTest.php
> Reduces verbosity when generating AstMap.

- README.md
Hi,
I add a line on the documentation for the Graphviz dependency on Windows.
> update Graphviz dependency for Windows

- Makefile
Tests command in Makefile not referenced
> fixed typo

- composer.json
- composer.lock
The `sensiolabs-de/astrunner` package is also [available on packagist.org](https://packagist.org/packages/sensiolabs-de/astrunner).
> drop no longer needed repositories

- composer.json
Just adds the missing deptrac description to the composer.json.
> Add description to composer file

- README.md
Just adds the appveyor status to the readme file.
> Add appveyor status to readme

- .travis.yml
- src/DependencyEmitter/BasicDependencyEmitter.php
- src/Tests/DependencyEmitter/BasicDependencyEmitterTest.php
- src/Tests/DependencyEmitter/Fixtures/Foo.php
> Prevent illegal offset warnings return types

- composer.lock
- src/Collector/MethodCollector.php
- src/DependencyEmitter/BasicDependencyEmitter.php
- src/RulesetEngine.php
- tests/Collector/InheritanceLevelCollectorTest.php
- tests/Collector/MethodCollectorTest.php
- tests/DependencyEmitter/EmitterTrait.php
~~https://github.com/sensiolabs-de/astrunner/pull/6 should be merged first~~ is merged
> Added more type-hints including for astrunner type-hints improvement

- README.md
- examples/DirectoryLayer.depfile.yml
- examples/Layer1/AnotherClassLikeAController.php
- examples/Layer1/SomeClass.php
- examples/Layer1/SomeClass2.php
- examples/Layer2/SomeOtherClass.php
- examples/Layer2/SomeOtherClass2.php
- services.xml
- src/Collector/DirectoryCollector.php
- src/Tests/Collector/DirectoryCollectorTest.php
see
https://github.com/sensiolabs-de/deptrac/pull/135
https://github.com/sensiolabs-de/deptrac/pull/108
> Feature directory collector

- composer.json
- composer.lock
depends on https://github.com/sensiolabs-de/astrunner/pull/9
> upgrade to php-parser 4.0

- composer.json
- composer.lock
> upgrade astrunner to v1.0

- box.json.dist
- deptrac.php
> use git-version as app version + enable php and json compactor

- .travis.yml
This PR
💁‍♂️ For reference, see https://github.com/phpstan/phpstan/compare/0.10.6...0.11.2.
> Enhancement: Update phpstan/phpstan

- tests/Collector/ClassNameCollectorTest.php
- tests/Collector/ClassNameRegexCollectorTest.php
- tests/Collector/RegistryTest.php
- tests/Configuration/ConfigurationCollectorTest.php
- tests/OutputFormatter/OutputFormatterInputTest.php
- tests/OutputFormatterFactoryTest.php
> Enhancement: Apply @PHPUnit60Migration:risky ruleset

- composer.lock
```
- Updating nikic/php-parser (v4.1.1) to nikic/php-parser (v4.2.1)
- Updating symfony/filesystem (v4.2.2) to symfony/filesystem (v4.2.3)
- Updating symfony/config (v4.2.2) to symfony/config (v4.2.3)
- Updating symfony/console (v4.2.2) to symfony/console (v4.2.3)
- Updating symfony/dependency-injection (v4.2.2) to symfony/dependency-injection (v4.2.3)
- Updating symfony/event-dispatcher (v4.2.2) to symfony/event-dispatcher (v4.2.3)
- Updating symfony/finder (v4.2.2) to symfony/finder (v4.2.3)
- Updating symfony/options-resolver (v4.2.2) to symfony/options-resolver (v4.2.3)
- Updating symfony/yaml (v4.2.2) to symfony/yaml (v4.2.3)
- Updating sebastian/environment (4.0.1) to sebastian/environment (4.1.0)
- Updating sebastian/diff (3.0.1) to sebastian/diff (3.0.2)
- Updating …
```
> dependency updates

- .travis.yml
- config/cache.xml
- deptrac.php
- src/AstRunner/AstParser/AstFileReferenceFileCache.php
- src/Console/Application.php
- src/Console/Command/AnalyzeCommand.php
> added input parameter option for cache file

- README.md
> Fix outdated graphviz download link in README

- src/FileResolver.php
- src/PathNameFilterIterator.php
- tests/PathNameFilterIteratorTest.php
> improve file exclusion

- src/Console/Command/AnalyzeCommand.php
- src/OutputFormatter/ConsoleOutputFormatter.php
- src/Subscriber/ConsoleSubscriber.php
- tests/Subscriber/ConsoleSubscriberTest.php
Added option for disabling banner.
Added option for disabling progress bar.
Verbosity normal only shows banner, progress and result.
Verbosity verbose shows additional information.
Verbosity very verbose additionally shows collected files.
> Improve console output of analyze command.

- composer.json
- composer.lock
- config/services.xml
- src/AstRunner/AstMap/AstDependency.php
- src/AstRunner/AstParser/NikicPhpParser/AstClassReferenceResolver.php
- src/AstRunner/AstParser/NikicPhpParser/NikicPhpParser.php
- src/AstRunner/Resolver/AnnotationDependencyResolver.php
- src/AstRunner/Resolver/ClassDependencyResolver.php
- src/AstRunner/Resolver/NameScope.php
- src/AstRunner/Resolver/TypeResolver.php
- tests/AstRunner/Resolver/AnnotationDependencyResolverTest.php
- tests/AstRunner/Resolver/fixtures/AnnotationDependency.php
> annotation dependency resolver

- config/services.xml
- src/AstRunner/AstMap/AstDependency.php
- src/AstRunner/Resolver/ClassConstantResolver.php
- tests/AstRunner/Resolver/ClassConstantResolverTest.php
- tests/AstRunner/Resolver/fixtures/ClassConst.php
> class constant resolver

- config/services.xml
- src/AstRunner/AstMap/AstDependency.php
- src/AstRunner/Resolver/AnonymousClassResolver.php
- tests/AstRunner/Resolver/AnonymousClassResolverTest.php
- tests/AstRunner/Resolver/fixtures/AnonymousClass.php
> anonymous class resolver

- README.md
> Update documentation on bool collector to describe actual behaviour

- src/AstRunner/AstMap/AstFileReference.php
> Enhancement: Introduce temporary variable

- .php_cs.dist
> Enhancement: Keep rules sorted in .php_cs.dist

- src/AstRunner/AstParser/AstFileReferenceFileCache.php
- src/AstRunner/AstParser/NikicPhpParser/NikicPhpParser.php
- src/ClassNameLayerResolver.php
- src/Configuration/Configuration.php
- src/Configuration/ConfigurationLayer.php
- src/DependencyContext.php
- src/OutputFormatterFactory.php
- src/RulesetEngine.php
> Enhancement: Add return type declarations to closures

- config/services.xml
- src/AstRunner/AstParser/NikicPhpParser/AstClassReferenceResolver.php
- src/AstRunner/AstParser/NikicPhpParser/NikicPhpParser.php
- tests/AstRunner/Resolver/AnnotationDependencyResolverTest.php
- tests/AstRunner/Resolver/AnonymousClassResolverTest.php
- tests/AstRunner/Resolver/ClassConstantResolverTest.php
https://blackfire.io/profiles/compare/17f1bcf2-dc12-4a59-933f-4c9a93cc2da1/graph
> improve analysing performance

- src/Console/Command/AnalyzeCommand.php
Deptrac should be "stable" enough.
> remove banner

- composer.lock
- examples/symfony_depfile.yml
- src/OutputFormatter/JUnitOutputFormatter.php
> jUnit: report successful + uncovered testcases

- .github/workflows/continuous-integration.yml
- .php_cs.dist
- composer.json
- composer.lock
- deptrac.php
- src/Collector/Registry.php
- src/OutputFormatterFactory.php
> adds composer/xdebug-handler

- README.md
- src/Collector/BoolCollector.php
- src/Collector/CollectorInterface.php
- tests/Collector/BoolCollectorTest.php
resolves #111 
@theofidry thanks you for setting-up #111 originally. I cherry-picked all doc improvements :-)
> Add doc for MethodCollector and misc

- README.md
- config/services.php
- examples/Implements/Bar.php
- examples/Implements/Baz.php
- examples/Implements/Foo.php
- examples/implements.depfile.yaml
- src/AstRunner/AstMap/AstInherit.php
- src/AstRunner/AstMap/ClassLikeName.php
- src/AstRunner/AstParser/NikicPhpParser/ClassReferenceVisitor.php
- src/Collector/ImplementsCollector.php
- tests/AstRunner/AstMapFlattenGeneratorTest.php
- tests/Collector/ImplementsCollectorTest.php
> adds implements collector

- composer.lock
- src/AstRunner/Resolver/TypeResolver.php
- tests/AstRunner/Resolver/TypeResolverTest.php
> Bugfix: cover more DocBlock types

- README.md
See https://github.com/sensiolabs-de/deptrac/blob/master/src/Collector/ImplementsCollector.php#L45-L47
> Fixes key for implements Collector

- README.md
- src/AstRunner/AstMap/AstInherit.php
- src/Collector/ExtendsCollector.php
- src/Collector/InheritsCollector.php
- src/Collector/UsesCollector.php
- tests/Collector/ExtendsCollectorTest.php
- tests/Collector/InheritsCollectorTest.php
- tests/Collector/UsesCollectorTest.php
Fixes #309 
Adds 3 collectors:
`inherits` -- collects any inheritance type (implements, extends or trait use)
`extends` -- collects classes extending other classes or interfaces
`uses` -- collects classes using a trait
> Adds uses, extends and inherits collectors.

- src/AstRunner/AstParser/NikicPhpParser/ClassReferenceVisitor.php
- tests/AstRunner/AstMapGeneratorTest.php
- tests/AstRunner/Fixtures/Issue319.php
> differentiate between possible use types

- config/services.php
resolves #333 
This adds also 2 other missing collectors. The uses and inherits collector.
> Add missing Collectors into the container

- src/AstRunner/Resolver/TypeResolver.php
- tests/AstRunner/Resolver/TypeResolverTest.php
> ignore (psalm) pseudo types

- .php_cs.dist
- src/OutputFormatter/ConsoleOutputFormatter.php
- src/OutputFormatter/JUnitOutputFormatter.php
> Enhancement: Enable final_static_access fixer

- src/AstRunner/Resolver/TypeResolver.php
- tests/AstRunner/Resolver/TypeResolverTest.php
add Psalm pseudo types to avoid invalid Fqsen error
> add psalm pseudo-types

- src/OutputFormatter/GithubActionsOutputFormatter.php
- tests/OutputFormatter/GithubActionsOutputFormatterTest.php
> Add support for report skipped option in GithubActionsOutputFormatter

- src/OutputFormatter/TableOutputFormatter.php
- tests/OutputFormatter/TableOutputFormatterTest.php
> Add support for report skipped option in TableOutputFormatter

- README.md
- src/Console/Command/AnalyzeCommand.php
> Don't report skipped violations by default

- src/OutputFormatter/ConsoleOutputFormatter.php
- src/OutputFormatter/GithubActionsOutputFormatter.php
- src/OutputFormatter/GraphVizOutputFormatter.php
- src/OutputFormatter/JUnitOutputFormatter.php
- src/OutputFormatter/XMLOutputFormatter.php
- tests/OutputFormatter/ConsoleOutputFormatterTest.php
- tests/OutputFormatter/GithubActionsOutputFormatterTest.php
- tests/OutputFormatter/GraphVizOutputFormatterTest.php
- tests/OutputFormatter/JUnitOutputFormatterTest.php
- tests/OutputFormatter/XMLOutputFormatterTest.php
> Remove deprecated options

- src/OutputFormatter/ConsoleOutputFormatter.php
- src/OutputFormatter/TableOutputFormatter.php
- tests/OutputFormatter/ConsoleOutputFormatterTest.php
- tests/OutputFormatter/TableOutputFormatterTest.php
> Use TableOutputFormatter as default

- src/Console/Command/AnalyzeCommand.php
- src/OutputFormatterFactory.php
- tests/OutputFormatterFactoryTest.php
> Remove deprecated formatter options

- README.md
- src/AstRunner/Resolver/TypeResolver.php
- src/Configuration/example_configuration.yml
> fix fqsen type resolver

- composer.json
- composer.lock
- deptrac.php
> update xdebug-handler to v2

- src/LayerAnalyser.php
<details>
<pre>
1) Tests\Qossmic\Deptrac\LayerAnalyserTest::testAnalyze
104
Failed asserting that two arrays are identical.
105
--- Expected
106
+++ Actual
107
@@ @@
108
Array &0 (
109
-    0 => 'Tests\Qossmic\Deptrac\Fixtures\LayerAnalyser\ClassBar'
110
-    1 => 'Tests\Qossmic\Deptrac\Fixtures\LayerAnalyser\ClassFoo'
111
+    0 => 'Tests\Qossmic\Deptrac\Fixtures\LayerAnalyser\ClassFoo'
112
+    1 => 'Tests\Qossmic\Deptrac\Fixtures\LayerAnalyser\ClassBar'
113
)
</pre>
</details>
> fix randomly failing test in LayerAnalyerTest

- composer.lock
```
composer update symfony/config symfony/console \
symfony/dependency-injection symfony/event-dispatcher \
symfony/finder symfony/options-resolver symfony/yaml
```
Closes #556, #557, #558, #559, #560, #561, #562
> Update Symfony dependencies

- .github/workflows/build.yml
- .github/workflows/static-analysis.yml
- .github/workflows/test.yml
- README.md
> Switch default branch to main

- composer.json
- composer.lock
Prerequisite for https://github.com/qossmic/deptrac/issues/535
Tests are OK locally
Can build locally
> Update composer dependency for phpdocparser

- README.md
- config/services.php
- src/Console/Application.php
- src/Console/Command/DebugUnassignedCommand.php
- src/UnassignedAnalyser.php
- tests/Fixtures/UnassignedAnalyser/ClassBar.php
- tests/Fixtures/UnassignedAnalyser/ClassFoo.php
- tests/UnassignedAnalyserTest.php
> List unassigned classes

- README.md
- src/Console/Command/DebugClassLikeCommand.php
- src/Console/Command/DebugLayerCommand.php
- src/Console/Command/DebugUnassignedCommand.php
> Refactored debug output

- src/AstRunner/AstMap/AstDependency.php
- src/AstRunner/AstMap/ClassReferenceBuilder.php
- src/AstRunner/AstParser/NikicPhpParser/ClassReferenceVisitor.php
- tests/AstRunner/AstParser/NikicPhpParser/Fixtures/Attributes.php
- tests/AstRunner/AstParser/NikicPhpParser/NikicPhpParserTest.php
> Support for attributes

- src/AstRunner/Resolver/TypeResolver.php
- src/AstRunner/Resolver/TypeScope.php
> Fix things missed by rector

- .github/workflows/build.yml
- examples/Transitive.depfile.yaml
> Add e2e test for transitive dependencies

- .editorconfig
> editorconfig: Ignore trailing whitespace in tests

- .github/workflows/test.yml
- Makefile
> Run deptrac as part of the test suite

- depfile.baseline.yml
> Fix master

- src/Configuration/Definition.php
> fixed bug in merging hidden_layers

- config/services.php
Fixes: https://github.com/qossmic/deptrac/issues/671
> Add superglobal collector to services.php

- .phive/phars.xml
- Makefile
- infection.json.dist
- phpunit.xml.dist
- tests/Collector/BoolCollectorTest.php
- tests/Collector/ClassNameCollectorTest.php
- tests/Collector/ClassNameRegexCollectorTest.php
- tests/Collector/FunctionNameCollectorTest.php
- tests/Collector/InheritanceLevelCollectorTest.php
- tests/Collector/RegistryTest.php
- tests/Collector/SuperglobalCollectorTest.php
- tests/Dependency/InheritanceFlatterTest.php
- tests/MemoizedTokenLayerResolverTest.php
- tests/RulesetEngineTest.php
- tests/TokenLayerResolverTest.php
Upgrade PHPUnit 8.5 to 9.5 and replace Prophecy
> Upgrade PHPUnit

- src/Collector/DirectoryCollector.php
- tests/Collector/DirectoryCollectorTest.php
closes https://github.com/qossmic/deptrac/issues/635
> DirectoryCollector: Support OS agnostic paths

- .phive/phars.xml
- composer.lock
- phpstan-baseline.neon
- phpstan.neon.dist
- src/AstRunner/AstMap/AstInherit.php
- src/AstRunner/Resolver/TypeResolver.php
- src/Configuration/Configuration.php
Builds on #694
* Update composer dependencies
* Update phive dependencies
* Fix type issues reported by psalm and phpstan
* Set phpstan level to 8, as new level 9 introduces new issues that need to be fixed separately
Closes #694
> Update multiple dependencies.

- src/OutputFormatter/GraphVizOutputFormatter.php
> Update to support phpdocumentator/graphviz:2.0.0-beta1

- baseline.xml
- depfile.yaml
- docs/formatters.md
- src/Configuration/ConfigurationGraphViz.php
- src/Configuration/Definition.php
- src/OutputFormatter/GraphVizOutputFormatter.php
- tests/OutputFormatter/GraphVizOutputFormatterTest.php
- tests/OutputFormatter/data/graphviz-groups-point.dot
> Pointing to groups

- composer.json
- composer.lock
- src/OutputFormatter/GraphVizOutputFormatter.php
Updates the package for the next version and update the code to use the most up-to-date methods provided by the library.
> Update composer.json for phpdocumentator

- baseline.xml
- config/services.php
- depfile.yaml
- docs/collectors.md
- phpstan-baseline.neon
- src/Collector/BoolCollector.php
- src/Collector/ClassNameCollector.php
- src/Collector/ClassNameRegexCollector.php
- src/Collector/CollectorInterface.php
- src/Collector/DirectoryCollector.php
- src/Collector/ExtendsCollector.php
- src/Collector/FunctionNameCollector.php
- src/Collector/ImplementsCollector.php
- src/Collector/InheritanceLevelCollector.php
- src/Collector/InheritsCollector.php
- src/Collector/LayerCollector.php
- src/Collector/MethodCollector.php
- src/Collector/RegexCollector.php
- src/Collector/SuperglobalCollector.php
- src/Collector/UsesCollector.php
- src/Configuration/ConfigurationCollector.php
- src/Configuration/ConfigurationLayer.php
- src/TokenLayerResolver.php
- tests/Collector/BoolCollectorTest.php
- tests/Collector/LayerCollectorTest.php
- tests/TokenLayerResolverTest.php
> Layer collector

- src/RulesetEngine.php
> ReturnTypeWillChange support

- .phive/phars.xml
- Makefile
- src/AstRunner/AstMap.php
I will probably wait for the next update of humbug/box before merging to make sure that #763 is fully resolved.
> Update tools installed via phive.

- src/OutputFormatter/BaselineOutputFormatter.php
> Create baseline directory if it does not exist.

- .github/workflows/build.yml
- .github/workflows/static-analysis.yml
- .github/workflows/test.yml
- .phive/phars.xml
- .php-cs-fixer.dist.php
- Makefile
- composer.json
- composer.lock
- config/services.php
- src/AstRunner/AstParser/NikicPhpParser/FileReferenceVisitor.php
- src/FileResolver.php
- tests/PathNameFilterIteratorTest.php
* Move some tools to composer dev dependencies instead:
* php-cs-fixer
* phpstan
* psalm
* Update composer dependencies
> Upgrade tools and dependencies

- README.md
- docs/upgrade.md
- mkdocs.yml
> Add upgrade guide to docs and add install instructions to GitHub-README

- src/Layer/LayerResolver.php
Fixes #910
Sorry, my bad. No test, just manual testing to get it out ASAP.
> Fixes #910

- src/Console/Application.php
- src/DependencyInjection/ServiceContainerBuilder.php
There is no clear place to put this into documentation, however.
Fixes: #917
> Add option to clear cache

- src/Supportive/DependencyInjection/Configuration.php
- src/Supportive/DependencyInjection/DeptracExtension.php
- src/Supportive/OutputFormatter/Configuration/ConfigurationGraphViz.php
- src/Supportive/OutputFormatter/GraphVizOutputFormatter.php
- tests/Supportive/DependencyInjection/DeptracExtensionTest.php
- tests/Supportive/OutputFormatter/ConfigurationGraphVizTest.php
- tests/Supportive/OutputFormatter/GraphVizDotOutputFormatterTest.php
> Restore semantic formatter configuration.

- .github/workflows/build.yml
- .github/workflows/static-analysis.yml
- .github/workflows/test.yml
- README.md
- composer.json
- deptrac.php
- docs/contributing.md
- docs/index.md
Closes #906
I suspect that workflows will fail because GitHub will use the old workflow and not the applied changes in this PR. OK, it seems that I was wrong.
> Update to php 8.1

- tests/Core/InputCollector/FileInputCollectorTest.php
- tests/Core/InputCollector/PathNameFilterIteratorTest.php
- tests/Supportive/Console/ConsoleSubscriberTest.php
- tests/Supportive/Console/ProgressSubscriberTest.php
- tests/Supportive/OutputFormatter/GithubActionsOutputFormatterTest.php
- tests/Supportive/OutputFormatter/GraphVizDotOutputFormatterTest.php
- tests/Supportive/OutputFormatter/TableOutputFormatterTest.php
Patch the issue #586.
With this change all unittests are running on windows. Most of the Problems have been line ending related.
> Fix unittests for windows

- box.json.dist
Closes https://github.com/qossmic/deptrac-shim/issues/8
> Fix init not working in phar.

- config/services.php
> Fix missing service registration

- docs/extending_deptrac.md
- mkdocs.yml
> Extension documentation 

- src/Supportive/Console/Application.php
Tested locally, shorthand for config-file looks fine now.
> Use getOption instead getParameterOption on config file

- docs/collectors.md
> Updated CollectorInterface namespace in docs

- docs/configuration.md
> Update configuration.md typo

- composer.lock
- Closes #1170
- Closes #1169
- Closes #1168
- Closes #1167
- Closes #1166
- Closes #1161
- Closes #1159
- Closes #1154
- Closes #1153
- Closes #1152
- Closes #1146
- Closes #1145
> Combine updates

- .gitignore
- .php-cs-fixer.dist.php
- Makefile
- deptrac.baseline.yaml
- docker-compose.yaml
- docker/php/Dockerfile
- phpstan.neon.dist
- phpunit.xml.dist
- psalm.xml
I think having a working docker setup could help newcomers and myself ;-).
> add docker setup and move cache-files into .cache/

- src/Supportive/File/FileReader.php
#1158 @see https://github.com/phpstan/phpstan-src/pull/2094
I'm just implementing the performance optimization @staabm did for phpstan.
> #1158 - only read file once for filereader

- src/Core/Ast/Parser/NikicPhpParser/FileReferenceVisitor.php
- tests/Core/Ast/Parser/ClassDocBlockExtractorTest.php
- tests/Core/Ast/Parser/Fixtures/ClassDocBlockDependency.php
> Closes https://github.com/qossmic/deptrac/issues/1191

- .github/dependabot.yml
> dependabot group updates
