- src/Command/AnalyzeCommand.php
When running a deptrac analysis as part of a travis build the build passes even when the result shows violations.
The analysis should return a non-zero exit code when violations were found and otherwise return 0.
> Analysis with violations returns a 0 exit code.

- src/OutputFormatter/OutputFormatterInterface.php
Minor suggestion of changes while reviewing the interface:
- Attempt to give an explanation on what `::getName()` is used for (it's always a bit unclear when you have to implement a `::getName()` function, you never really now what kind of name is expected.
- Add missing return block (obvious that name is a string but could be nullable..., docblock removes all ambiguity)
> Review of OutputFormatterInterface

- README.md
In order to be able to build deptrac ```phar.readonly = Off``` is needed, otherwise the following exception will be thrown:
[UnexpectedValueException]                                                                                       
creating archive "~/deptrac/deptrac.phar" disabled by the php.ini setting phar.readonly
> Fix build php.ini documentation

- Makefile
This allows to overwrite the binaries. For example, on my system, I use `box.phar` instead of `box`. I can now build with
`make build BOX_BIN=box.phar`
> use variables for binaries in Makefile

- Makefile
No need for `--dev` option since it's deprecated and used by default.
> Remove composer deprecated option --dev

- composer.json
- composer.lock
Just alphabetically sort the composer packages to keep it more readable.
> Sort composer packages

- README.md
- composer.json
- composer.lock
- deptrac.php
- services.xml
- src/Command/SelfUpdateCommand.php
- src/Updater/DeptracStrategy.php
This is a proposal for the self-update command #13 to be used as base although it needs probably some modifications.
Since the latest ```deptrac.phar``` is hosted in ```http://get.sensiolabs.de/deptrac.phar```, I thought the following location can be used to indicate its version ```http://get.sensiolabs.de/deptrac.version``` (currently not existing and should be created by SensionLabs as they admin the continuous delivery process I guess), which will be used in the code to fetch the latest version and compare it with the running one.
@slde-flash Let me know, what do you think about this or if you need a more sophisticated solution :smiley:.
> Add self-update command

- src/Tests/Command/SelfUpdateCommandTest.php
This pull requests add some tests for the self-update command. 
The command itself was added as well in order to allow testing but there is a dedicated pull request for that, see #84.
> Add tests for self update command

- composer.json
PHPUnit 4.x is not guaranteed to be fully compatible with PHP 7.
However, PHPUnit 5.x does not support PHP 5.5.
> allow PHPUnit 5 too for forward compatibility

- src/DependencyEmitter/BasicDependencyEmitter.php
- src/Tests/DependencyEmitter/BasicDependencyEmitterTest.php
- src/Tests/DependencyEmitter/Fixtures/Foo.php
The emitter assumed that the `NullableType::$type` holds a `Name` node, this is however not the case as it is a plain string.
> Fixed parsing of nullable return types

- src/DependencyEmitter/BasicDependencyEmitter.php
> Prevent illegal offset warnings FQCN

- src/Configuration.php
- src/Tests/ConfigurationTest.php
IMO it's perfectly valid to not have to use the `exclude_files` options if, for example, source and test directory are separated and you do not want to exclude any source files. Currently, you would have to set this option explicitly to just be an empty sequence.
> allow the "exclude_files" option to be omitted

- README.md
- services.xml
- src/Collector/ClassNameRegexCollector.php
- src/Collector/DirectoryCollector.php
- src/Collector/MethodCollector.php
- tests/Collector/ClassNameRegexCollectorTest.php
- tests/Collector/DirectoryCollectorTest.php
- tests/Collector/MethodCollectorTest.php
> #139 - use your own regex pattern

- .gitignore
- README.md
- services.xml
- src/ClassNameLayerResolver.php
- src/ClassNameLayerResolverCacheDecorator.php
- src/ClassNameLayerResolverInterface.php
- src/DependencyContext.php
- src/OutputFormatter/JUnitOutputFormatter.php
- tests/OutputFormatter/JUnitOutputFormatterTest.php
- tests/OutputFormatter/data/expected-junit-report_1.xml
- tests/OutputFormatter/data/expected-junit-report_2.xml
- tests/OutputFormatter/data/expected-junit-report_3.xml
> Add output formatter to create junit reports

- .gitignore
- Makefile
- box.json.dist
I'm actually not sure if you were using Box 2 or Box 3, but in any case the following works with Box 3.1.
List of the changes:
- Simplify the `box.json.dist` config by removing the redundant settings `stub` and `output`
- Remove the `directories` setting of the `box.json.dist` config allowing Box to do the auto-discovery of the files to include. This allows Box to easily remove the dev dependencies so there is no longer a need to do a `composer install --no-dev`
- Simplify the `make build`
- Remove the unnecessary `chmod +x` since the generated PHAR is already an executable
- Remove the now unnecessary `composer install --no-dev`
- Rename `box build` to `box compile` (the previous command name has been deprecated)
- Add the files generated by `make build` to `.gitignore`
> Upgrade to Box3

- box.json.dist
When gz-compression is enable the phar-file size will be reduced to just 632 KB instead of 3.24 MB.
It might not be a thing having a dependency on zlib as it is should be enabled/installed by default (on linux/unix).
> enable gz compression + php-scoper

- README.md
- examples/SkipViolations.yml
- examples/SkipViolations/SkipViolations.php
- src/Command/AnalyzeCommand.php
- src/Configuration/Configuration.php
- src/Configuration/ConfigurationSkippedViolation.php
- src/DependencyContext.php
- src/OutputFormatter/ConsoleOutputFormatter.php
- src/OutputFormatter/JUnitOutputFormatter.php
- src/RulesetEngine.php
- tests/Configuration/ConfigurationSkippedViolationTest.php
- tests/Configuration/ConfigurationTest.php
- tests/DependencyContextTest.php
- tests/OutputFormatter/ConsoleOutputFormatterTest.php
- tests/OutputFormatter/JUnitOutputFormatterTest.php
- tests/OutputFormatter/data/expected-junit-report-with-skipped-violations.xml
- tests/OutputFormatter/data/expected-junit-report_1.xml
- tests/OutputFormatter/data/expected-junit-report_2.xml
- tests/RulesetEngineTest.php
Initial implementation of #199
Implement possibility to skip class dependency violation in `depfile.yml`. There will be new configuration section `skip_violations` (maybe `skipped_violations` better?). The developer can configure it in the following way:
```yaml
skip_violations:
Library\LibClass:
- Core\CoreClass
- Core\AnotherClass
```
`skip_violations` section contains associative array where key (`Library\LibClass`) is the name of dependant class and values (`Core\CoreClass`, `Core\AnotherClass`) are dependency classes.
There might be implemented possibility for PHP functions dependency as well. In this case, we can specify functions names instead of class names. PHP allows to create functions with names which can be equal to class names in the same namespace:
```php
<?php
namespace …
```
> Implemented skip violations

- .gitignore
- README.md
- box.json.dist
- composer.json
- composer.lock
- config/cache.xml
- config/services.xml
- deptrac.php
- services.xml
- src/AstRunner/AstParser/AstParserInterface.php
- src/AstRunner/AstParser/NikicPhpParser/CacheableFileParser.php
- src/AstRunner/AstParser/NikicPhpParser/FileParser.php
- src/AstRunner/AstParser/NikicPhpParser/FileParserInterface.php
- src/AstRunner/AstParser/NikicPhpParser/NikicPhpParser.php
- src/AstRunner/AstParser/NikicPhpParser/ParserFactory.php
- src/AstRunner/AstRunner.php
- src/Command/AnalyzeCommand.php
- src/Console/Application.php
- src/Console/Command/AnalyzeCommand.php
- src/Console/Command/InitCommand.php
- src/Subscriber/CacheableFileSubscriber.php
- tests/AstRunner/AstMapFlattenGeneratorTest.php
- tests/AstRunner/AstMapGeneratorTest.php
- tests/DependencyEmitter/EmitterTrait.php
> caching parsed files

- Makefile
`SHA1SUM` wasn't aligned with the others, and now it is.
> Fix alignment

- phpunit.xml.dist
> Fix: Remove non-applicable exclude configuration

- .php_cs.dist
- src/AstRunner/AstParser/AstFileReferenceFileCache.php
- src/Configuration/Configuration.php
- src/Configuration/ConfigurationLayer.php
- src/OutputFormatterFactory.php
This PR
💁‍♂ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.15.1#usage:
>**static_lambda**
>
>Lambdas not (indirect) referencing `$this` must be declared `static`.
>
>_Risky rule: risky when using `->bindTo` on lambdas without referencing to `$this`._
> Enhancement: Enable static_lambda fixer

- src/Configuration/Exception/FileCannotBeParsedAsYamlException.php
- src/Configuration/Loader.php
- tests/Configuration/Exception/FileCannotBeParsedAsYamlExceptionTest.php
- tests/Configuration/LoaderTest.php
This PR
Running
```
$ php deptrac.php analyze composer.lock
```
yields
```
deptrac is alpha, not production ready.
please help us and report feedback / bugs.
In Parser.php line 391:
Unable to parse at line 1 (near "{").
analyze [--formatter-graphviz [FORMATTER-GRAPHVIZ]] [--formatter-graphviz-display [FORMATTER-GRAPHVIZ-DISPLAY]] [--formatter-graphviz-dump-image [FORMATTER-GRAPHVIZ-DUMP-IMAGE]] [--formatter-graphviz-dump-dot [FORMATTER-GRAPHVIZ-DUMP-DOT]] [--formatter-graphviz-dump-html [FORMATTER-GRAPHVIZ-DUMP-HTML]] [--formatter-console [FORMATTER-CONSOLE]] [--formatter-junit [FORMATTER-JUNIT]] [--formatter-junit-dump-xml [FORMATTER-JUNIT-DUMP-XML]] [--no-banner] [--no-progress] [--] [<depfile>]
```
Running
```
$ php deptrac.php analyze composer.lock
```
yields
```
deptrac is alpha, not …
```
> Enhancement: Throw exception when configuration cannot be parsed as yaml

- src/OutputFormatter/ConsoleOutputFormatter.php
- src/OutputFormatter/OutputFormatterInput.php
- tests/OutputFormatter/ConsoleOutputFormatterTest.php
- tests/OutputFormatter/OutputFormatterInputTest.php
resolves #231
```
Symfony\Bundle\DebugBundle\Command\ServerDumpPlaceholderCommand has uncovered dependency on Closure (DebugBundle)
/Users/simon/Projects/symfony/src/Symfony/Component/Console/Command/Command.php::281
Symfony\Component\Console\Command\Command::28 ->
Closure::281
Symfony\Bundle\DebugBundle\Command\ServerDumpPlaceholderCommand has uncovered dependency on ReflectionFunction (DebugBundle)
/Users/simon/Projects/symfony/src/Symfony/Component/Console/Command/Command.php::282
Symfony\Component\Console\Command\Command::28 ->
ReflectionFunction::282
Symfony\Bundle\DebugBundle\Command\ServerDumpPlaceholderCommand has uncovered dependency on Closure (DebugBundle)
/Users/simon/Projects/symfony/src/Symfony/Component/Console/Command/Command.php::284 …
```
> report uncovered dependencies

- .github/workflows/continuous-integration.yml
- .github/workflows/test-flag-fail-on-uncovered.sh
- examples/Uncovered.depfile.yaml
- examples/Uncovered/InternalClasses.php
- src/Console/Command/AnalyzeCommand.php
- src/RulesetEngine/Context.php
Here is a patch to allow failure if uncovered cases are found.
I could not find any test to cover the changes made to the command nor the Context object, if tests are mandatory please explain where should I fit a test for this use-case.
> Add flag --fail-on-uncovered (closes #306)

- phpunit.xml.dist
- src/Env.php
- src/OutputFormatter/ConsoleOutputFormatter.php
- src/OutputFormatter/GithubActionsOutputFormatter.php
- tests/EmptyEnv.php
- tests/OutputFormatter/ConsoleOutputFormatterTest.php
- tests/OutputFormatter/GithubActionsOutputFormatterTest.php
- tests/phpt/Env.phpt
- tests/phpt/GithubActionsOutputFormatterIsActiveByDefaultInGitHubActionsEnvironment.phpt
> Enable GithubActionsOutputFormatter by default in GithubActions environment

- README.md
- src/OutputFormatter/GithubActionsOutputFormatter.php
- tests/OutputFormatter/ConsoleOutputFormatterTest.php
- tests/OutputFormatter/GithubActionsOutputFormatterTest.php
> Add option to report uncovered dependencies for GitHubActionFormatter

- .gitignore
- README.md
- box.json.dist
- config/cache.php
- deptrac.php
- scoper.inc.php
- src/Collector/Registry.php
- tests/Collector/RegistryTest.php
This patch enables the registry to load collectors by FQCN if not already present in the cache the missing object gets initiated and added to the cache.
Should fix #164
> Load Collectors by FQCN

- src/Configuration/Configuration.php
- src/Configuration/Exception/InvalidConfigurationException.php
- tests/Configuration/ConfigurationTest.php
- tests/Configuration/Exception/InvalidConfigurationExceptionTest.php
This PR
💁‍♂️ Not sure if is by design, but I can't see a reason why anyone would need to define multiple layers with the same name. Instead they probably want to define multiple collectors.
> Fix: Reject duplicate layer names

- src/Configuration/Configuration.php
- src/Configuration/Exception/InvalidConfigurationException.php
- tests/Configuration/ConfigurationTest.php
- tests/Configuration/Exception/InvalidConfigurationExceptionTest.php
- tests/RulesetEngineTest.php
This PR
💁‍♂️ During the weekend I ran into an issue because I had a typo in a ruleset.
> Fix: Reject rule sets referencing unknown layers

- src/OutputFormatter/GithubActionsOutputFormatter.php
- tests/OutputFormatter/GithubActionsOutputFormatterTest.php
> github actions show inherit path

- README.md
- config/services.php
- src/Configuration/Exception/BaselineFileCannotBeReadException.php
- src/Configuration/Loader.php
- src/Configuration/Loader/YmlFileLoader.php
- src/OutputFormatter/BaselineOutputFormatter.php
- tests/Configuration/Fixtures/Uncovered.depfile.yaml
- tests/Configuration/Fixtures/baseline-import.yml
- tests/Configuration/Fixtures/baseline-main.yml
- tests/Configuration/Fixtures/non-existent-baseline.yml
- tests/Configuration/Loader/YmlFileLoaderTest.php
- tests/Configuration/LoaderTest.php
- tests/OutputFormatter/BaselineOutputFormatterTest.php
- tests/OutputFormatter/data/expected-baseline-report_1.yml
- tests/OutputFormatter/data/expected-baseline-report_2.yml
- tests/OutputFormatter/data/expected-baseline-report_3.yml
- tests/OutputFormatter/data/expected-baseline-report_4.yml
- tests/OutputFormatter/data/generated-baseline.yml
Hello,
here is a possible solution to create a baseline for Deptrac.
With this simple formatter it's possible to use deptrac in a CI/CD environment without fixing all existing violations
> Introduce BaselineOutputFormatter

- config/services.php
- src/AstRunner/Resolver/PropertyTypeResolver.php
- src/AstRunner/Resolver/TypeResolver.php
- tests/AstRunner/Resolver/AnnotationDependencyResolverTest.php
- tests/AstRunner/Resolver/AnonymousClassResolverTest.php
- tests/AstRunner/Resolver/ClassConstantResolverTest.php
- tests/AstRunner/Resolver/Fixtures/AnnotationDependency.php
- tests/AstRunner/Resolver/Fixtures/AnonymousClass.php
- tests/AstRunner/Resolver/Fixtures/ClassConst.php
- tests/AstRunner/Resolver/Fixtures/PropertyTypeDependency.php
- tests/AstRunner/Resolver/PropertyTypeResolverTest.php
- tests/AstRunner/Resolver/fixtures/PropertyTypeDependency.php
> Support non annotated property type

- tests/OutputFormatter/BaselineOutputFormatterTest.php
- tests/OutputFormatter/data/generated-baseline.yml
Currently, `tests/OutputFormatter/data/generated-baseline.yml` is committed that result of basicDataProvider data set #0.
After developer running test, `generated-baseline.yml` file will be chagned with other data set.
eg.
```
$ git diff
diff --git a/tests/OutputFormatter/data/generated-baseline.yml b/tests/OutputFormatter/data/generated-baseline.yml
index 1c28cb2..c3af77a 100644
--- a/tests/OutputFormatter/data/generated-baseline.yml
+++ b/tests/OutputFormatter/data/generated-baseline.yml
@@ -1,3 +1,3 @@
skip_violations:
-  ClassA:
-    ClassB: ClassB
+  OriginalA:
+    - OriginalB
```
Because, PHPUnit would randomly test for dataProvider data set.
```
$ ./tools/phpunit.phar --testdox --filter "testBasic" tests/OutputFormatter/BaselineOutputFormatterTest.php
PHPUnit 8.5.13 by Sebastian …
```
> replace useless specific output file to temp file at test.

- README.md
- src/Console/Command/AnalyzeCommand.php
- src/OutputFormatter/ConsoleOutputFormatter.php
- tests/OutputFormatter/ConsoleOutputFormatterTest.php
These changes propose a new option that allows hiding skipped violations from the console formatter's output. For depfiles with a long baseline, it is hard to spot new violations amongst skipped ones.
> Add option to not print skipped violations in ConsoleOutputFormatter

- src/OutputFormatter/ConsoleOutputFormatter.php
- src/OutputFormatter/GithubActionsOutputFormatter.php
- src/OutputFormatter/TableOutputFormatter.php
- src/RulesetEngine.php
- src/RulesetEngine/Context.php
- src/RulesetEngine/Warning.php
- tests/OutputFormatter/BaselineOutputFormatterTest.php
- tests/OutputFormatter/ConsoleOutputFormatterTest.php
- tests/OutputFormatter/GithubActionsOutputFormatterTest.php
- tests/OutputFormatter/GraphVizOutputFormatterTest.php
- tests/OutputFormatter/JUnitOutputFormatterTest.php
- tests/OutputFormatter/TableOutputFormatterTest.php
- tests/OutputFormatter/XMLOutputFormatterTest.php
> [POC] report warnings about classes are in two or more layers

- README.md
as is, the example runs into a error:
```
50/50 [============================] 100%
In ClassNameRegexCollector.php line 24:
ClassNameRegexCollector needs the regex configuration.
```
> readme: fix `classNameRegex` example

- src/Console/Command/AnalyzeCommand.php
- src/OutputFormatter/GithubActionsOutputFormatter.php
- src/OutputFormatter/TableOutputFormatter.php
- tests/OutputFormatter/GithubActionsOutputFormatterTest.php
- tests/OutputFormatter/TableOutputFormatterTest.php
> Report uncovered as errors with GithubActionOutputFormatter

- README.md
- config/services.php
- src/OutputFormatter/JsonOutputFormatter.php
- tests/LayerAnalyserTest.php
- tests/OutputFormatter/JsonOutputFormatterTest.php
- tests/OutputFormatter/data/expected-json-report_1.json
- tests/OutputFormatter/data/expected-json-report_2.json
- tests/OutputFormatter/data/expected-json-report_3.json
- tests/OutputFormatter/data/expected-json-report_4.json
- tests/OutputFormatter/data/expected-json-report_5.json
Added json formatter. 
By default, formatter dumps information to STDOUT, so you can use command line tools to handle it.
Optionally we can use flag `--json-dump=<path>` to dumps information in file.
Output format is close to [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting#printing-a-json-report) or [PhpStan](https://github.com/phpstan/phpstan/commit/2f5b724d2da978b8cf24a133fb04ba9e2171571c) formats.
> Add JSON formatter

- src/OutputFormatter/JUnitOutputFormatter.php
- tests/OutputFormatter/JUnitOutputFormatterTest.php
- tests/OutputFormatter/data/expected-junit-report-with-unmatched-violations.xml
Closes #568
Adding this (sample) output at the beginning of the file.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
<testsuite id="0" package="" name="Unmatched skipped violations" hostname="localhost" tests="0" failures="0" skipped="0" errors="4" time="0">
<failure message="Skipped violation &quot;TrainingCompass\Saas\Dashboards\Controls\Dashboard\LayoutControl&quot; for &quot;TrainingCompass\Saas\Branding\Personal\DashboardPresenter&quot; was not matched." type="WARNING"/>
<failure message="Skipped violation &quot;TrainingCompass\Saas\Dashboards\Controls\Dashboard\LayoutControlFactory&quot; for &quot;TrainingCompass\Saas\Branding\Personal\DashboardPresenter&quot; was not matched." type="WARNING"/>
<failure message="Skipped violation …
```
> JUnit output formatter - unmatched skipped violations

- src/AstRunner/AstMap/ClassReferenceBuilder.php
- src/AstRunner/AstMap/FileReferenceBuilder.php
- src/AstRunner/AstParser/NikicPhpParser/ClassReferenceVisitor.php
- src/AstRunner/Resolver/AnnotationDependencyResolver.php
- src/AstRunner/Resolver/TypeResolver.php
- tests/AstRunner/Resolver/AnnotationDependencyResolverTest.php
- tests/AstRunner/Resolver/Fixtures/AnnotationDependency.php
- tests/AstRunner/Resolver/TypeResolverTest.php
Closes #535
It is far from complete support, but it extends current support for generics and `@template` annotation
What is in:
- Method template types (but the template type it should be resolved to is ignored)
- list generic (`list<*>`)
- resolving "pre-generic type" `resolved<*>`
- template type on class resolved recognized in method
What is still missing:
- resolving the template type
> Basic template type and generic support

- README.md
- src/Configuration/ConfigurationRuleset.php
- src/RulesetEngine.php
- tests/Configuration/ConfigurationRulesetTest.php
Closes: #202
Closes: #158
In the end, since I was able to contain the changes to one class, it is easier than expected.
> Transitive dependencies

- src/Configuration/Configuration.php
It was missing E2E tests, so went unnoticed.
> BUGFIX: Forgotten config validation for transitive dependencies

- examples/Transitive.depfile.yaml
- examples/Transitive/Bar.php
- examples/Transitive/Bat.php
- examples/Transitive/Baz.php
- examples/Transitive/Foo.php
Examples act as e2e during build. I tried this on 0.14.0 to confirm the issue as well as the current main to verify the fix.
Follow up to #618
> Add example for transitive dependencies.

- .editorconfig
- CHANGELOG.md
- Makefile
https://github.com/symplify/changelog-linker is no longer maintained. I'd rather not use the suggested replacement ergebnis/github-changelog, because [according to the README](https://github.com/ergebnis/github-changelog#when-will-it-work-for-me) it will not work with squash merges, which I regularly used when a PR has more than 1 commit. The ruby gem https://github.com/github-changelog-generator/github-changelog-generator is one of the proposed alternatives.
I propose switching to github_changelog_generator and regenerate the changelog with it.
> Replace changelog-linker with github_changelog_generator

- .gitignore
- Makefile
- depfile.baseline.yml
- depfile.yaml
Use deptrac to analyse deptrac.
> Eat your own dog food (use deptrac on deptrac)

- src/Configuration/Exception/FileCannotBeParsedAsYamlException.php
- src/Configuration/Loader/YmlFileLoader.php
- tests/Configuration/Exception/FileCannotBeParsedAsYamlExceptionTest.php
- tests/Configuration/Fixtures/depfile-syntax-error.yaml
- tests/Configuration/Loader/YmlFileLoaderTest.php
fixes https://github.com/qossmic/deptrac/issues/661
more details in yaml syntax errors
> Report yaml syntax errors in more detail

- deptrac.php
Installing vias shim is great and all, but there are reasons why one might now want to do so. From the top of my head:
- Not wanting to wait for a release. You might pin to a commit instead and get new features before a tagged release
- It is a strong precursor for writing extensions to the package.
> Make library usable as is without shim

- .github/workflows/build.yml
- .github/workflows/test.yml
- composer.json
This is my 1st contribution to this project so I'm no sure I'm doing right:
1. Should I also add an entry in the changelog?
2. How does the publication into https://github.com/qossmic/deptrac-shim work?
> feat: support php 8.1

- src/Console/Command/AnalyseCommand.php
- src/Console/Command/DebugLayerCommand.php
- src/Console/Command/DebugTokenCommand.php
- src/Console/Command/DefaultDepFileTrait.php
See: https://github.com/qossmic/deptrac/issues/689
- Use getDefaultFile in DebugCommands.
- DebugLayer layer is now optional, if no layer is provided all layers will be printed
> Move getDefaultFile to trait

- src/Configuration/ConfigurationAnalyser.php
- tests/Configuration/ConfigurationAnalyserTest.php
Resolves #707
Based on the tests it was the expected behavior, but it is not intuitive. So I changed it to an intuitive version and wrote another test for manually adding the `use` analyzer via deprecated config.
> Fix issue #707

- src/OutputFormatter/GraphVizOutputFormatter.php
This restores the behavior from the previous graphviz library, where dumping the image into a new directory, would create it instead of throwing an error.
> Option `--graphviz-dump-image` creates directory

- composer.json
- composer.lock
We now create a conflict that makes it impossible to install packages dependent on PHPStan major release version. This fixes the issue.
> Update to support PHPStan v1

- baseline.xml
- composer.lock
- phpstan-baseline.neon
- src/FileResolver.php
- src/PathNameFilterIterator.php
- src/Subscriber/ProgressSubscriber.php
```
- Upgrading composer/xdebug-handler (2.0.2 => 2.0.3)
- Upgrading nikic/php-parser (v4.13.1 => v4.13.2)
- Upgrading symfony/config (v5.3.11 => v5.4.0)
- Upgrading symfony/console (v5.3.11 => v5.4.0)
- Upgrading symfony/dependency-injection (v5.3.11 => v5.4.0)
- Upgrading symfony/event-dispatcher (v5.3.11 => v5.4.0)
- Upgrading symfony/filesystem (v5.3.4 => v5.4.0)
- Upgrading symfony/finder (v5.3.7 => v5.4.0)
- Upgrading symfony/options-resolver (v5.3.7 => v5.4.0)
- Upgrading symfony/string (v5.3.10 => v5.4.0)
- Upgrading symfony/yaml (v5.3.11 => v5.4.0)
```
phpstan reports errors due to a misleading doc block in php-parser.
I chose to ignore them as the behavior (as far as I can tell) has not changed.
> Upgrading dependencies

- depfile.baseline.yml
- depfile.yaml
Refactors ConsoleSubscriber to ensure it uses our own Output object instead of relying on Symfony\Console\Output
> Depfile use output instead of symfony

- src/Configuration/Loader.php
Fixes #766
No test, because this section is deprecated anyway and I'm planning on removing it in the release after the next one.
> Fix Invalid type for path "deptrac.parameters.analyzer".

- README.md
When creating the docs site, I forgot to change link to an image in README.md
> Fix outdated image reference

- baseline.xml
- depfile.baseline.yml
- src/Collector/BoolCollector.php
- src/Collector/ClassNameCollector.php
- src/Collector/ClassNameRegexCollector.php
- src/Collector/CollectorInterface.php
- src/Collector/DirectoryCollector.php
- src/Collector/ExtendsCollector.php
- src/Collector/FunctionNameCollector.php
- src/Collector/ImplementsCollector.php
- src/Collector/InheritanceLevelCollector.php
- src/Collector/InheritsCollector.php
- src/Collector/LayerCollector.php
- src/Collector/MethodCollector.php
- src/Collector/RegexCollector.php
- src/Collector/SuperglobalCollector.php
- src/Collector/UsesCollector.php
- src/TokenLayerResolver.php
- tests/Collector/LayerCollectorTest.php
- tests/Console/DummyCollector.php
To make each layer resolution only once and then use that result in collectors that need it. Instead of making the collectors resolve the layers again.
> Refactor of TokenLayerResolver

- src/Console/Command/DefaultDepFileTrait.php
Removes fallback to old default file name, when specified config-file is not found. Subsequently, the file loader will throw the `CouldNotReadFileException.php` for the expected filename.
Fixes #789
> Fix wrong file name in error message

- src/DependencyEmitter/FQDNIndexNode.php
- src/DependencyEmitter/UsesDependencyEmitter.php
- tests/DependencyEmitter/Fixtures/FQDNIsSubstring/FQDN/SomeClass.php
- tests/DependencyEmitter/Fixtures/FQDNIsSubstring/Foo.php
- tests/DependencyEmitter/UsesDependencyEmitterTest.php
- tests/FQDNIndexNodeTest.php
Closes  #798
```
real    0m8,316s
user    0m7,007s
sys     0m1,129s
```
versus vanila 0.19.1^
```
real    7m38,165s
user    7m32,888s
sys     0m1,887s
```
> Fix performance issue

- src/Console/Command/DebugLayerCommand.php
- src/Console/Command/DebugLayerOptions.php
- src/Console/Command/DebugTokenCommand.php
- src/Console/Command/DebugUnassignedCommand.php
- src/Console/Command/DefaultDepFileTrait.php
Make depfile argument optional in all commands.
Bug was caused by the command still expecting the required, deprecated depfile argument.
> Fix debug commands when using new config-file option

- docs/index.md
> Update docs to reflect 0.19 depfile structure

- .phive/phars.xml
- Makefile
- scoper.inc.php
Fixes #839 
Fixes #818 
Fixes #763
> Update box from 3.14 to 3.16

- docs/formatters.md
- src/OutputFormatter/GraphVizOutputImageFormatter.php
Tested locally (macOS) with svg, jpg & pdf and worked fine. When picking a format that is not valid, graphviz will conveniently tell us the supported formats:
```
[ERROR]                                                                                                                
Output formatter graphviz-image threw an Exception:                                                            
Message: Unable to display output: An error occurred while creating the graph; GraphViz returned: Format:      
"html" not recognized. Use one of: bmp canon cgimage cmap cmapx cmapx_np dot dot_json eps exr fig gd gd2 gif gv
icns ico imap imap_np ismap jp2 jpe jpeg jpg json json0 mp pct pdf pic pict plain plain-ext png pov ps ps2 psd 
sgi svg svgz tga tif tiff tk vdx vml vmlz vrml wbmp webp xdot …
```
> Allow graphviz-image to output image in different formats.

- src/Analyser/AstMapExtractor.php
`AstMap` must absolutely necessarily be cached for many use cases, where you are calling multiple analyzers within one command. Both internally to Deptrac and for Extensions.
> AstMap In Memory Cache

- config/services.php
- src/Configuration/FormatterConfiguration.php
- src/OutputFormatter/CodeclimateOutputFormatter.php
- src/OutputFormatter/GraphVizOutputFormatter.php
- tests/OutputFormatter/CodeclimateOutputFormatterTest.php
- tests/OutputFormatter/GraphVizDotOutputFormatterTest.php
Add a Class for formatter configuration, so that extension formatters can autowire it. Symfony is not friendly to autowiring non-class variables.
> Add formatter configuration, so that extensions can autowire it.

- .github/workflows/build.yml
- .github/workflows/test.yml
- .phive/phars.xml
- Makefile
- composer.json
- composer.lock
- docs/contributing.md
- tests/phpt/Env.phpt
- tests/phpt/GithubActionsOutputFormatterIsActiveByDefaultInGitHubActionsEnvironment.phpt
> Get rid of phive

- config/services.php
- src/Analyser/EventHandler/AllowDependencyHandler.php
- src/Layer/LayerProvider.php
Making `AllowDependencyHandler::getAllowedLayers` public and static. This helper method is useful for integrations.
> Make allowed layer resolution public

- config/services.php
- docs/collectors.md
- docs/examples/GlobCollector.depfile.yaml
- src/Layer/Collector/CollectorTypes.php
- src/Layer/Collector/GlobCollector.php
- tests/Layer/Collector/GlobCollectorTest.php
> New collector for glob patterns

- config/services.php
- docs/depfile.md
- src/Ast/AstMap/DependencyToken.php
- src/Ast/AstMap/ReferenceBuilder.php
- src/Ast/Parser/NikicPhpParser/FileReferenceVisitor.php
- src/Dependency/Emitter/ClassDependencyEmitter.php
- src/Dependency/Emitter/EmitterTypes.php
- src/Dependency/Emitter/FileDependencyEmitter.php
- src/Dependency/Emitter/FunctionCallDependencyEmitter.php
- src/Dependency/Emitter/FunctionDependencyEmitter.php
- src/DependencyInjection/Configuration.php
- tests/Dependency/Emitter/Fixtures/Bar.php
- tests/Dependency/Emitter/Fixtures/Baz.php
- tests/Dependency/Emitter/FunctionCallDependencyEmitterTest.php
> Make AST map aware of custom function calls

- src/Ast/AstMap/ReferenceBuilder.php
- src/Ast/Parser/NikicPhpParser/FileReferenceVisitor.php
- tests/Ast/Parser/NikicPhpParser/Fixtures/TemplateTypes.php
- tests/Ast/Parser/NikicPhpParser/NikicPhpParserTest.php
> Resolution of template vars defined at function-like level

- src/Core/Layer/LayerResolver.php
Fixes wrongly recognized violation.
Open Tasks:
- [ ] Add tests
> Fix issue when using layer-collector

- src/Supportive/File/Dumper.php
- tests/Supportive/File/DumperTest.php
- tests/Supportive/File/Fixtures/deptrac.yaml
> Fix init with existing file.

- deptrac.yaml
After our last dependency upgrade we reuse the original event names from Symfony with the "kernel."-prefix. Without the proper tag these listeners will not be registered automatically.
> Fix tag for event_listener.

- docs/collectors.md
- docs/index.md
it fixes some broken links on https://qossmic.github.io/deptrac/
> Fix docs: use correct case in markdown filenames

- src/Supportive/Console/Application.php
Set help as default command if params "--help" or "-h" will passed and cannot load configuration
> Fix --help doesn't work if deptrac.yaml file is missing issue

- Makefile
- composer.json
- composer.lock
- infection.json.dist
- src/Core/Ast/AstMap/ClassLike/ClassLikeReferenceBuilder.php
- src/Core/Ast/AstMap/FunctionLike/FunctionLikeReferenceBuilder.php
- src/Core/Ast/Parser/TypeResolver.php
- src/Supportive/OutputFormatter/BaselineOutputFormatter.php
Closes: #1020
Installed `roave-infection-static-analysis-plugin` that checks escaped mutants against static-analysis tools. If they would not pass SA, it kills them. Currently, supports only Psalm and not PHPStan
> Mutation coverage improvements

- src/Supportive/Console/Application.php
I overwrote --help input option and added throws annotation according to psalm audit
> Override --help input option and add throws annotation according to psalm audit

- config/services.php
- deptrac.config.php
- deptrac.yaml
- docs/collectors.md
- src/Contract/Config/Collector/ComposerConfig.php
- src/Contract/Config/CollectorType.php
- src/Core/Layer/Collector/ComposerCollector.php
- src/Core/Layer/Collector/ComposerFilesParser.php
- src/Supportive/Console/Command/AnalyseRunner.php
- tests/Core/Layer/Collector/ComposerCollectorTest.php
- tests/Core/Layer/Collector/data/composer.json
- tests/Core/Layer/Collector/data/composer.lock
> Composer Collector

- src/Core/Layer/Collector/ComposerCollector.php
#1158 
We parsed the composer.lock everytime we checked via satisfy. @patrickkusebauch 
Before:
After:
> #1158 - only init new ComposerFileParser once per composer.lock

- src/Core/Ast/Parser/Extractors/VariableExtractor.php
----
before/after diff:
refs https://github.com/qossmic/deptrac/issues/1158
> Call `SuperGlobalToken::allowedNames()` just once

- src/Contract/Analyser/EventHelper.php
- tests/Contract/Analyser/EventHelperTest.php
> fix #1226 - skipped multiple violations in one file

- Makefile
- composer.json
- deptrac
Add a convenient way to use the php version of deptrac.
Another nice side effect would be, that the php-config can now be named `deptrac.php`
> "deptrac" as composer bin

- src/Supportive/OutputFormatter/Configuration/ConfigurationGraphViz.php
- src/Supportive/OutputFormatter/GraphVizOutputFormatter.php
PR #951 did not fully fix #949. Reason for this is that the Symfony container compiler skips loading extensions for which no configuration has been made. This in turn means that the Deptrac Configuration class is never processed and its default values are not being populated.
> do not crash the GraphViz formatter if no config is given

- src/Core/Ast/Parser/NikicPhpParser/FileReferenceVisitor.php
refs https://github.com/qossmic/deptrac/issues/1158
> Prevent excessive php-doc parsing in FileReferenceVisitor

- src/Core/Layer/Collector/ComposerCollector.php
- src/Core/Layer/Collector/ComposerFilesParser.php
- tests/Core/Layer/Collector/ComposerCollectorTest.php
Throw InvalidCollectorDefinitionException if ComposerCollector could not locate a package
Fixes: https://github.com/qossmic/deptrac/issues/1230
> Composer collector exception when package does not exist 

- src/Supportive/DependencyInjection/ServiceContainerBuilder.php
Fixes https://github.com/qossmic/deptrac/issues/1301
Putting all into a single `if` does make things little bit unreadable so I decided to change it to a more understandable if statements: https://github.com/qossmic/deptrac/pull/1302/commits/e25210949cf950a7eba0b959626d34b7295d52eb
> Add creating of cache directory if not exists

- README.md
GitHub has added a copy command functionality leaving the dollar signs in adds friction when copying the commands
> Remove dollar signs from readme.md console examples

- composer.json
- composer.lock
This PR addresses problems parsing PHP 8.3 syntax, by bumping the version of `php-parser` to the latest patch release.
There continue to be deprecation warnings from `phpdocumentor/graphviz` but this project appears to be abandoned.
Other than that this is working for me perfectly on my project recently upgraded to PHP 8.3.
Resolves #1341
> Bump PHP Parser version to support PHP 8.3

- .github/workflows/build.yml
- .github/workflows/static-analysis.yml
- .github/workflows/test.yml
Update github pipeline to support php8.3
> add php8.3 to pipeline

- tests/Core/Analyser/EventHandler/DependsOnInternalTokenTest.php
- tests/Core/Ast/Parser/NikicPhpParser/NikicPhpParserTest.php
- tests/Core/Layer/Collector/TagValueRegexCollectorTest.php
This PR introduces a TagValueRegexCollector that allows layers to be defined based on the presence or value of doc tags like @deprecated.
All tags present in the doc block are exposed on ClassLikeReference and FunctionReference, for use by collectors and event handlers.
Note that this changs the way #1319 and #1318 should be implemented.
> Define layers based on doc tags

- composer.json
- composer.lock
Due to not having an up to date shim version and instead needing to require this repository as no other solution is there at this moment, see here #1345, this package is blocking from installing it alongside other packages.
> Update jetbrains/phpstorm-stubs from 2022.2 to 2023.3 as minimal version

- src/Supportive/OutputFormatter/ConsoleOutputFormatter.php
- tests/Supportive/OutputFormatter/ConsoleOutputFormatterTest.php
This is minor usability improvement. 
At least **PHPStorm does not jump to the line** when I copy current output (with double colon). With single colon, it does.
> ConsoleFormatter: output 'file:line' to allow jump-to-line in IDEs

- .github/workflows/static-analysis.yml
- Makefile
- composer-dependency-analyser.php
- composer.json
- composer.lock
Hi, I tested your repository with [composer-dependency-analyser](https://github.com/shipmonk-rnd/composer-dependency-analyser) and it found some **shadow dependencies**:
-------------
All those seem valid to me, so I added those to composer and the tool to CI to avoid possible issues in future.
> Add composer-dependency-analyser (fix shadow dependencies)
